FROM nvcr.io/nvidia/pytorch:25.06-py3
# For cuda capabilities sm80 and more recent

RUN apt update && apt upgrade -y
RUN apt install -y bc vim git

RUN git config --global user.email "roehr@simula.no"
RUN git config --global user.name "Thomas Roehr"

WORKDIR /naic-workspace/resources/
RUN git clone -b main https://github.com/2maz/naic-bench naic-bench
RUN pip install -e ./naic-bench

WORKDIR /naic-workspace
