FROM python:3.10-bookworm

RUN apt update && apt upgrade -y
RUN apt install -y bc vim git

RUN git config --global user.email "roehr@simula.no"
RUN git config --global user.name "Thomas Roehr"

RUN pip3 install torch torchvision --index-url https://download.pytorch.org/whl/cpu

WORKDIR /naic-workspace/resources/
RUN git clone -b main https://github.com/2maz/naic-bench naic-bench
RUN pip install -e ./naic-bench

WORKDIR /naic-workspace
